<?php

/**
 * @file
 * AWS SQS module functions.
 */

/**
 * The maximum length for a queue name prefix. Since a queue name in SQS can be
 * no more than 80 characters, we restrict the prefix to fewer in order to leave
 * reasonable length for actual queue names.
 *
 * @see http://aws.amazon.com/sqs/faqs/
 */
define('AWS_SQS_QUEUE_NAME_PREFIX_MAXLENGTH', 60);

/**
 * Implements hook_menu().
 */
function aws_sqs_menu() {
  $items = array();

  $items['admin/config/system/aws-queue'] = array(
    'title' => 'Amazon SQS Settings',
    'description' => 'Configure your Amazon SQS Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('aws_sqs_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'aws_sqs.admin.inc',
  );
  return $items;
}
